apiVersion: v1
kind: Service
metadata:
  labels:
    app: pihole
  name: pihole-service
  namespace: pihole
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: pihole
  ports:
  - name: pihole-http
    port: 80
    protocol: TCP
    targetPort: 80 #Container port
  - name: pihole-ssl
    port: 443
    targetPort: 443
    protocol: TCP  
  - name: pihole-tcp-dns
    port: 53
    targetPort: 53
    protocol: TCP    
  - name: pihole-udp-dns
    port: 53
    protocol: UDP
    targetPort: 53