apiVersion: v1
kind: Service
metadata:
  labels:
    app: pihole
  name: pihole-service
  namespace: pihole
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: pihole
  ports:
  - name: pihole-tcp-dns
    targetPort: 53
    port: 53
    protocol: TCP
  - name: pihole-http
    port: 80
    protocol: TCP
    targetPort: 80 #Container port
  - name: pihole-udp-dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: pihole-ssl
    port: 443
    targetPort: 443
    protocol: TCP  
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-tcp
  labels:
    app: pihole
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: dns
      port: 53
      targetPort: 53
      protocol: TCP
  selector:
    app: pihole
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-udp
  labels:
    app: pihole
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: pihole-dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
  selector:
    app: pihole   