apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole-tls
  namespace: pihole
  annotations:
    avp.kubernetes.io/path: "argocd/data/argocd-vault-plugin/pihole"

spec:
  secretName: pihole-tls
  issuerRef:
    name: pihole-letsencrypt-prod
  duration: 2160h0m0s
  renewBefore: 360h0m0s  
  dnsNames:
  - <path:argocd/data/argocd-vault-plugin/pihole#url>
